# Generated by Django 6.1 on 2026-08-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('ocupada', 'Ocupada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='reservada', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='hotel.habitacion')),
            ],
        ),
    ]
